# Discord settings:

bot_token: "$DISCORD_BOT_TOKEN"
client_id: "$DISCORD_CLIENT_ID"
status_message: "$DISCORD_STATUS_MESSAGE"

max_text: 100000
max_images: 1
max_messages: 25

use_plain_responses: false
allow_dms: true


debug_prompt: false
test_echo_mode: false

permissions:
  users:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []


# LLM settings:

providers:
  # Remote providers:
  google:
    base_url: https://generativelanguage.googleapis.com/v1beta/openai
    api_key: $GEMINI_API_KEY
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 

  # Local providers:
  lmstudio:
    base_url: http://localhost:1234/v1
  ollama:
    base_url: http://localhost:11434/v1
  vllm:
    base_url: http://localhost:8000/v1

models:
  google/gemini-2.5-flash: {}
  google/gemini-2.5-pro: 
    reasoning_effort: high


system_prompt: "$BOT_SYSTEM_PROMPT"